### ISSUE TITLE
Replace gvfs

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#45]
gnome-online-accounts: 3.36.0
        gvfs: 1.30.4_4
        libgdata: 0.17.9_1
        webkit2-gtk3: 2.30.1
        wpebackend-fdo: 1.4.1

103 MiB

**Comment by DamjanJovanovic** [comment]
What package are those dependencies for?

Neither gvfs git nor gvfs-1.47.90 source code contain the word "webkit".

webkit2-gtk3-2.30.2's required-by (and their entire ancestry of required-by) does not include gvfs.

What ports branch is this from?

**Comment by probonopd** [comment]
D'uh, I should have written this down. I think this was what happened when I tried to `sudo pkg install gvfs` on a FreeBSD 12.1 system.

**Comment by DamjanJovanovic** [comment]
The GOOGLE option adds this dependency chain:

devel/gvfs -> devel/libgdata -> net/gnome-online-accounts -> webkit2-gtk3

GOOGLE was set to off by default by this change, you probably tried gvfs before that:
```
commit f05c0025bbec89a4867d557bdda399857447d4d8
Author: bapt <bapt@FreeBSD.org>
Date:   Tue Oct 20 18:23:31 2020 +0000

    Remove GOOGLE option forgotten in previous commit
```

**Comment by probonopd** [comment]
Thank you very much. This kind of stuff is what I mean with "gvfs is entangled with a stack we don't want in helloSystem".

**Comment by DamjanJovanovic** [comment]
You're welcome. I still think you get further by understanding the software stack, and then customizing it to your requirements.

"Keep your friends close, keep your enemies closer." If we monitored GNOME's development activity, we would know about these problems before they get unleashed on poor users. If we studied and developed gvfs further, we could make it work with Qt WebEngine if need be, without upstream help.

"Cloning doesn't work against a fast competitor", Eric Schmidt, ex-CEO of Google in his "Unwinnable Wars" talk. Consider how a decade of Btrfs development failed to out-compete ZFS, and it took LLVM $50 million dollars and many years to develop Clang to the point where it began out-competing GCC. By comparison, one 8000 line project, bsdisks, quickly got every file manager on every desktop working better than HAL did, not because it reimplemented the entire GNOME stack, but because it developed one small component in just the right place, that got both gvfs and Solid singing and dancing to our tune.

**Comment by probonopd** [comment]
I need to learn more about `bsdisks`.

**Comment by DamjanJovanovic** [comment]
It looks somewhat like this. gvfs and Solid use libudisks to make DBus calls to the UDisks2 DBus service, which uses udev (now part of systemd), and various Linux kernel subsystems to expose devices, partitions, filesystems and operations and events on them over DBus. The deeper you go, the more it becomes a Linux-only setup.

bsdisks pretends to be UDisks2, implementing the same DBus functions, but using FreeBSD technologies like devd, CAM, and GEOM underneath, it can mount ZFS; software above is none the wiser.

![image](https://user-images.githubusercontent.com/4454328/111873752-a28c3a80-899a-11eb-9c6c-f12132402778.png)

Written in C++ with Qt, which makes DBus development particularly easy, it's only about 8000 lines compared to udisks2's 38000+ lines of C/glib. It doesn't do everything yet, there is no RAID, swap, it can't format drives, etc. but those APIs don't seem generally useful, I think they're there just for GNOME Disks to consume.

**Comment by probonopd** [comment]
> Written in C++ with Qt, which makes DBus development particularly easy, it's only about 8000 lines compared to udisks2's 38000+ lines of C/glib.

Now we are takling :-)

**Comment by DamjanJovanovic** [comment]
I believe Filer should work with bsdisks (report if not), but it has to use DBus.

Use at least bsdisks version 0.25, released a few days ago.

**Comment by DamjanJovanovic** [comment]
Also don't be scared of D-Bus. It's not the prettiest but it's organized and you get used to it. The entire object tree can be inspected. It's well tooled and scriptable. All traffic can be monitored with dbus-monitor. It's a heaven send compared to Microsoft's COM, in which traffic can't be monitored, there is little to no tooling and scripting, and you have to dig through the Windows registry to find things.

**Comment by probonopd** [comment]
Yes, and since many existing applications depend on it, I guess we just have to live with it for now. Still I find it way too convoluted. That whole `/` vs `.` thing alone.

**Comment by DamjanJovanovic** [comment]
The system bus should allow root and user processes to communicate. Only session buses are specific to user login sessions. A process can be on multiple buses, eg. gvfs is on the session bus for desktop apps to access it, and on the system bus to call UDisks2/bsdisks.

Each bus connection has a bus name like ":1.2", and can also request a nicer name like "org.freedesktop.NetworkManager" if exporting a service. Within a service, it exports objects, in a hierarchy of paths similar to a filesystem. Those objects are only unique to that service, not globally unique, which is why you always specify the bus name too when calling them. Objects have interfaces, and each interface has properties that can be read and/or written, and methods that can be called.

Only paths to objects have "/", everything else has ".":
some.service -> /path/to/object -> some.interface.and.method

dbus-send --print-reply --dest=some.service /path/to/object some.interface.and.method

**Comment by probonopd** [comment]
Yes, maybe it's just me but I find all of this utterly confusing. What is a path and what is an object and why are they not one and the same. Why do I need separate buses.

**Comment by DamjanJovanovic** [comment]
> Yes, maybe it's just me but I find all of this utterly confusing. What is a path and what is an object and why are they not one and the same. Why do I need separate buses.

![image](https://user-images.githubusercontent.com/4454328/112086890-b485fd00-8b95-11eb-8313-2ecb77a81ebf.png)

Separate session buses for users allow multi-seat and thin client configurations, as well as (in theory) secure communication between eg. apps and keyring. System buses are for global system-wide state, though in practice they're not always used that way, eg. Pulseaudio was criticized for using the session bus for audio instead of the system bus (even though audio is global in a single-user system) and breaking audio in apps running as a different user account (eg. some people ran Wine as a separate user to isolate its files from their main account) (don't know if it still does).

**Comment by linuxkettle** [comment]
> 38000+ lines of C/glib

30 is enough to make my head hurt.  
In other words, I'm no help here.

**Comment by probonopd** [comment]
We could use `sshfs` to mount SSH shares. That would have the added benefit that not only Filer, but all applications could access them from a path, e.g., inside `/media`, like every other volume.

To make this happen, we need to use the `SSH_ASKPASS` environment variable.

But: How can we get the equivalent of

![image](https://user-images.githubusercontent.com/2480569/201463155-3c1af138-9d70-4f6c-88b5-6d5dd1715dcd.png)

which currently pops up when accessing ssh via Filer? Since these strings are not in Filer source code, they must be coming from somewhere else... gvfs!

https://github.com/GNOME/gvfs/blob/ab4d7ba1da44ab94e05c74ac9f3ad2835e402768/daemon/gvfsbackendsftp.c#L934

How can we achieve the same thing but without gvfs?

**Comment by probonopd** [comment]
I have it working using [lxqt-openssh-askpass/](https://github.com/lxqt/lxqt-openssh-askpass/).

![image](https://user-images.githubusercontent.com/2480569/201465183-451854b9-b767-4463-8dd3-dc2510774779.png)

![image](https://user-images.githubusercontent.com/2480569/201465198-08c28f56-205c-4ed4-b62e-66f026bf35a9.png)

The dialogs could be nicer, but it's a start.

**Comment by probonopd** [comment]
Now we need a way for Filer to learn about Zeroconf without Gnome-ish dependencies, and show sftp services here: 

![image](https://user-images.githubusercontent.com/2480569/201468352-f4a22700-5708-49d6-845a-9f58dd9c78d3.png)

**Comment by probonopd** [comment]
The whole gfvs is an overcomplicated mess.

Just using FUSE sshfs and the like is so much more Unix philosophy.

I am so sick and tired of cryptic messages like this that point to other complicated mess:

```
(process:11003): GVFS-WARNING **: 11:03:14.196: The peer-to-peer connection failed: Fehler beim Holen der Informationen für Datei »/var/run/user/1001/gvfsd«: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
```

**Comment by grahamperrin** [comment]
> We could use `sshfs` …

Can anyone direct us to a server, for test purposes?

Primarily, to tell what happens when two or more people aim for concurrent edition of a single file. 

IIRC, there's loss of data with only one winner.

**Comment by probonopd** [comment]
Possibly. Is that handled better by gvfs?

**Comment by grahamperrin** [comment]
> … on a local filesystem? …

Most relevant is probably [fcntl(2)](https://www.freebsd.org/cgi/man.cgi?query=fcntl&sektion=2&manpath=FreeBSD): 

>> … Several operations are available for doing	advisory file locking; …

**Comment by grahamperrin** [comment]
> … handled differently by gvfs? …

Maybe more useful to think about things that are _not_ fixed, or enhanced, to work with GVFS. 

Resolved, fixed (2016-02-11): 

* Document Foundation bug [56544 – FILEOPEN: Lock file is not created on samba share (via gvfs)](https://bugs.documentfoundation.org/show_bug.cgi?id=56544)

**Comment by probonopd** [comment]
```
sudo pkg unlock gvfs 
sudo pkg unlock hellosystem-essential-packages
sudo pkg remove gvfs
```

As a result

* Way fewer processes are running, less RAM consumption
* `computer:///` is no longer populated in Filer
* Trash does not work anymore in Filer, __we need to reimplement it__
* Mounted devices are not shown on the desktop, __however they are still shown in the non-spatial Filer sidebar__ -- we need to find a way to do a similar thing on the desktop!
